# Generated by Django 4.1.4 on 2023-01-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("Age", models.IntegerField(max_length=2)),
                ("Active", models.BooleanField(default=True)),
                ("Brother", models.BooleanField(default=False)),
                ("Attendant1", models.CharField(max_length=40)),
                ("Attendant2", models.CharField(max_length=40)),
            ],
        ),
    ]
