# Generated by Django 4.1.4 on 2023-01-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player", name="Address", field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="Email",
            field=models.EmailField(max_length=254, null=True, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="player",
            name="FatherProf",
            field=models.CharField(
                max_length=60, null=True, verbose_name="Fathers profession"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="Price",
            field=models.DecimalField(decimal_places=2, default=350, max_digits=5),
        ),
        migrations.AddField(
            model_name="player",
            name="Type",
            field=models.CharField(
                choices=[("Civil", "Civil"), ("Military", "Military")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="player", name="Age", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="player",
            name="Attendant1",
            field=models.CharField(max_length=40, null=True, verbose_name="Parent"),
        ),
        migrations.AlterField(
            model_name="player",
            name="Attendant2",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Additional Parent"
            ),
        ),
    ]
