# Generated by Django 4.1.4 on 2023-01-02 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_attendance_coach_renter_session_sport_transaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="player",
            field=models.ManyToManyField(null=True, to="pages.player"),
        ),
        migrations.AddField(
            model_name="attendance",
            name="session",
            field=models.ManyToManyField(null=True, to="pages.session"),
        ),
        migrations.AddField(
            model_name="attendance",
            name="sport",
            field=models.ManyToManyField(null=True, to="pages.sport"),
        ),
        migrations.AddField(
            model_name="coach",
            name="CPhone",
            field=models.CharField(
                max_length=14, null=True, verbose_name="Phone number"
            ),
        ),
        migrations.AddField(
            model_name="coach",
            name="Sessions",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pages.session",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="PPhone",
            field=models.CharField(
                max_length=14, null=True, verbose_name="Phone number"
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="sessions",
            field=models.ManyToManyField(to="pages.session"),
        ),
        migrations.AddField(
            model_name="player",
            name="sport",
            field=models.ManyToManyField(to="pages.sport"),
        ),
        migrations.AddField(
            model_name="renter",
            name="RPhone",
            field=models.CharField(
                max_length=14, null=True, verbose_name="Phone number"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="sport",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="pages.sport"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="player",
            field=models.ManyToManyField(null=True, to="pages.player"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="sport",
            field=models.ManyToManyField(null=True, to="pages.sport"),
        ),
        migrations.AlterField(
            model_name="session",
            name="SName",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Coral", "Coral"),
                    ("Guitar", "Guitar"),
                    ("Violine", "Violine"),
                    ("Act", "Act"),
                    ("Piano", "Piano"),
                ],
                max_length=100,
                null=True,
                verbose_name="Music Session Name",
            ),
        ),
        migrations.AlterField(
            model_name="sport",
            name="Forl",
            field=models.BooleanField(default=False, verbose_name="For Ladies"),
        ),
    ]
