# Generated by Django 4.1.4 on 2023-01-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0004_attendance_player_attendance_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance", name="Date", field=models.DateField(),
        ),
        migrations.RemoveField(model_name="coach", name="Sessions",),
        migrations.AlterField(
            model_name="renter",
            name="Fees",
            field=models.DecimalField(
                decimal_places=4, max_digits=30, verbose_name="Rent price"
            ),
        ),
        migrations.RemoveField(model_name="session", name="sport",),
        migrations.AlterField(
            model_name="sport",
            name="PricCivil",
            field=models.DecimalField(
                decimal_places=4, max_digits=200, verbose_name="Civil price"
            ),
        ),
        migrations.AlterField(
            model_name="sport",
            name="PricMil",
            field=models.DecimalField(
                decimal_places=4, max_digits=200, verbose_name="Military price"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="Fees",
            field=models.DecimalField(decimal_places=4, max_digits=13),
        ),
        migrations.AddField(
            model_name="coach",
            name="Sessions",
            field=models.ManyToManyField(null=True, to="pages.session"),
        ),
        migrations.AddField(
            model_name="session",
            name="sport",
            field=models.ManyToManyField(null=True, to="pages.sport"),
        ),
    ]
