# Generated by Django 4.1.4 on 2023-01-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_alter_attendance_date_remove_coach_sessions_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="attendance", name="Date",),
    ]
