# Generated by Django 4.1.4 on 2023-01-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_remove_attendance_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="attendance", name="player",),
        migrations.RemoveField(model_name="attendance", name="session",),
    ]
