# Generated by Django 4.1.4 on 2023-01-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_remove_attendance_player_remove_attendance_session"),
    ]

    operations = [
        migrations.RemoveField(model_name="attendance", name="sport",),
        migrations.AddField(
            model_name="attendance",
            name="spor",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
