# Generated by Django 4.1.4 on 2023-01-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0008_remove_attendance_sport_attendance_spor"),
    ]

    operations = [
        migrations.RemoveField(model_name="attendance", name="spor",),
        migrations.AddField(
            model_name="attendance",
            name="player",
            field=models.ManyToManyField(null=True, to="pages.player"),
        ),
        migrations.AddField(
            model_name="attendance",
            name="session",
            field=models.ManyToManyField(null=True, to="pages.session"),
        ),
    ]
