# Generated by Django 4.1.4 on 2023-01-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_remove_attendance_spor_attendance_player_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="attendance", name="session",),
        migrations.AddField(
            model_name="attendance",
            name="sport",
            field=models.ManyToManyField(null=True, to="pages.sport"),
        ),
    ]
