# Generated by Django 4.1.4 on 2023-01-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_remove_attendance_session_attendance_sport"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="session",
            field=models.ManyToManyField(null=True, to="pages.session"),
        ),
        migrations.AddField(
            model_name="attendance",
            name="spor",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
