# Generated by Django 4.1.4 on 2023-01-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0013_remove_renter_rtphone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="Name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
